const songexample = {
  _id: { $oid: "670c228568b55693ff532a06" },
  title: "Wagon Wheel",
  artist: "Song Artist",
  sections: {
    "Verse-1": {
      title: "Verse 1",
      lines: [
        {
          words: [
            { text: "Headin'", chord: { letter: "A", quality: "" } },
            { text: "down" },
            { text: "south" },
            { text: "to" },
            { text: "the" },
            { text: "land", chord: { letter: "E", quality: "" } },
            { text: "of" },
            { text: "the" },
            { text: "pines" },
          ],
        },
        {
          words: [
            { text: "I'm" },
            { text: "thumbin'", chord: { letter: "F#m", quality: "" } },
            { text: "my" },
            { text: "way" },
            { text: "into" },
            { text: "North", chord: { letter: "D", quality: "" } },
            { text: "Caroline" },
          ],
        },
        {
          words: [
            { text: "Starin'", chord: { letter: "C", quality: "" } },
            { text: "up" },
            { text: "the" },
            { text: "road", chord: { letter: "D", quality: "" } },
            { text: "and" },
            { text: "pray" },
            { text: "to" },
            { text: "God" },
            { text: "I" },
            { text: "see" },
            { text: "headlights" },
          ],
        },
        { words: [{ text: "" }] },
        {
          words: [
            { text: "I" },
            { text: "made", chord: { letter: "G", quality: "" } },
            { text: "it" },
            { text: "down" },
            { text: "the" },
            { text: "coast", chord: { letter: "D", quality: "" } },
            { text: "in" },
            { text: "seventeen", chord: { letter: "A", quality: "" } },
            { text: "hours", chord: { letter: "G", quality: "" } },
          ],
        },
        {
          words: [
            { text: "Pickin'" },
            { text: "me" },
            { text: "a" },
            { text: "bouquet" },
            { text: "of" },
            { text: "dogwood" },
            { text: "flowers" },
          ],
        },
        {
          words: [
            { text: "And" },
            { text: "I'm" },
            { text: "a-hopin'", chord: { letter: "G#", quality: "" } },
            { text: "for" },
            { text: "Raleigh," },
            { text: "I" },
            { text: "can" },
            { text: "see", chord: { letter: "G", quality: "" } },
            { text: "my" },
            { text: "baby" },
            { text: "tonight", chord: { letter: "C", quality: "" } },
          ],
        },
      ],
    },
  },
  order: [{ sectionName: "Verse-1", showSectionTitleOnly: false }],
  createdAt: "2024-10-13T19:41:56.959Z",
  isDeleted: false,
  createdBy: "66c3bbf1f4d5c5a16e8b89f8",
  key: { letter: "C", quality: "" },
};
